name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate date-based tags
        id: date
        run: |
          echo "date_tag=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
          echo "datetime_tag=$(date +'%Y%m%d-%H%M')" >> $GITHUB_OUTPUT

      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/cbown75/synology-csi
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ steps.date.outputs.date_tag }},enable={{is_default_branch}}
            type=raw,value=${{ steps.date.outputs.datetime_tag }},enable={{is_default_branch}}
            type=ref,event=branch,suffix=-${{ steps.date.outputs.date_tag }}
            type=ref,event=pr,suffix=-${{ steps.date.outputs.date_tag }}
            type=semver,prefix=v,pattern={{version}}
          labels: org.opencontainers.image.source=https://github.com/cbown75/synology-csi-talos

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
